### ISSUE TITLE
Pipeline feature to scan leaks on S3 configuration

### ISSUE THREAD

**Issue by lpsm-dev** [sa7mon/S3Scanner#114]
Is it possible use this tool as a pipeline job?

**Comment by sa7mon** [comment]
I’m not sure what you mean by “pipeline job”. In the CI/CD sense? It’s a Python tool so you can run it anywhere you can run Python

**Comment by lpmatos** [comment]
Sorry, it would be a pipeline job that run in a CI-CD tool. The point is: this CLI has a feature that favors its use in CI environments?

For example: running the command `s3scanner scan -b <my-bucket>` I can have the output `<my-buckey>| bucket_exists | AuthUsers: [], AllUsers: []`. In a CI context it would be interesting we have a parameter that would return a failure if the scan showed some unexpected result.

**Comment by sa7mon** [comment]
Thank you for your bug report. I have just merged the pull request for complete re-write of this tool in Go so this issue is likely no longer applicable.

I would encourage you to try out the new version either by checking out the `main` branch or downloading the new release once I tag it. If you encounter errors with the new version, please open a new issue.
