### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by ansidorov** [sa7mon/S3Scanner#119]
Good afternoon.
Thank you very much for a great tool.
It would be nice to be able to get a report in json format for the convenience of scan automation. 
Do you plan to add such functionality?

**Comment by sa7mon** [comment]
I've thought about it for a long time - I'm just not sure the best way to handle it. It's possible for the tool to be scanning for a long time and be cancelled so I'm not sure if the whole thing should be wrapped in an array.

The two options would basically be:
```
[
    { "name": "myBucket", "exists": true, "auth_users": ["ReadACP"], "all_users": ["Read", "WriteACP"]},
    { "name": "myBucket2", "exists": true, "auth_users": ["ReadACP"], "all_users": ["Read", "WriteACP"]}
]
```

```
{ "name": "myBucket", "exists": true, "auth_users": ["ReadACP"], "all_users": ["Read", "WriteACP"]}
{ "name": "myBucket2", "exists": true, "auth_users": ["ReadACP"], "all_users": ["Read", "WriteACP"]}
```

Which option do you think would work better

**Comment by ansidorov** [comment]
The second log format is more popular with various tools

**Comment by Savvy95** [comment]
Don't use the first option as it is vulnerable to JSON Hijacking if used
incorrectly

Thanks for a great tool.

**Comment by sa7mon** [comment]
Could you elaborate on “JSON hijacking”? I’ve never heard the term before

**Comment by Savvy95** [comment]
If JSON is used in a web application, and is vulnerable, an attacker may be
able to steal sensitive information from an unsuspecting victim. If the
JSON won't be used in a web app, then this issue becomes a moot point. I
just thought that since you won't know how people will use the JSON data
that you should know.

Here's a link that can demystify it:
https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/json-hijacking-demystified/


Thanks

**Comment by sa7mon** [comment]
Thank you for your bug report. I have just merged the pull request for complete re-write of this tool in Go and the new version includes a JSON output option.
