### ISSUE TITLE
threads bug ?

### ISSUE THREAD

**Issue by d4op** [sa7mon/S3Scanner#130]
i start with --threads 200 or -t 200 and it says everytime dumping with 4 threads ?
bug?

**Comment by sa7mon** [comment]
Whoops, looks like it always _prints_ that it's using 4 threads.

https://github.com/sa7mon/S3Scanner/blob/fafa30a3bd35b496b3f7db9bfc35b75a8a06bcd1/S3Scanner/S3Service.py#L278

I'll fix this, but yeah it is actually dumping with as many threads as you specify.

**Comment by sa7mon** [comment]
Thank you for your bug report. I have just merged the pull request for complete re-write of this tool in Go so this issue is likely no longer applicable.

I would encourage you to try out the new version either by checking out the `main` branch or downloading the new release once I tag it. If you encounter errors with the new version, please open a new issue.
